version: '3.9'
services:
  comment-services:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0.4
    command: --bind_ip_all
    ports:
      - "27017:27017"
